"""
Affiliate models: AffiliateProgram, AffiliateLink, Commission.
"""

import uuid
import shortuuid
from django.conf import settings
from django.db import models


class AffiliateProgram(models.Model):
    """
    Affiliate program configured by a seller for their products.
    Defines commission rates and rules.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    seller = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="affiliate_programs",
    )
    product = models.OneToOneField(
        "products.DigitalProduct",
        on_delete=models.CASCADE,
        related_name="affiliate_program",
    )
    commission_rate = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=10.00,
        help_text="Commission percentage for affiliates.",
    )
    cookie_duration_days = models.PositiveIntegerField(
        default=30,
        help_text="Days the affiliate cookie remains active.",
    )
    minimum_payout = models.DecimalField(
        max_digits=10, decimal_places=2, default=10.00
    )
    is_active = models.BooleanField(default=True)
    terms = models.TextField(
        blank=True,
        help_text="Terms and conditions for the affiliate program.",
    )
    total_affiliates = models.PositiveIntegerField(default=0)
    total_referrals = models.PositiveIntegerField(default=0)
    total_commissions_paid = models.DecimalField(
        max_digits=12, decimal_places=2, default=0.00
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "affiliate_programs"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Affiliate: {self.product.title} ({self.commission_rate}%)"


class AffiliateLink(models.Model):
    """
    Unique referral link generated by an affiliate for a product.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    program = models.ForeignKey(
        AffiliateProgram,
        on_delete=models.CASCADE,
        related_name="links",
    )
    affiliate = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="affiliate_links",
    )
    code = models.CharField(
        max_length=20, unique=True, db_index=True
    )
    is_active = models.BooleanField(default=True)
    click_count = models.PositiveIntegerField(default=0)
    conversion_count = models.PositiveIntegerField(default=0)
    total_earned = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "affiliate_links"
        ordering = ["-created_at"]
        unique_together = ["program", "affiliate"]

    def __str__(self):
        return f"{self.affiliate.email} -> {self.program.product.title}"

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = shortuuid.uuid()[:10].upper()
        super().save(*args, **kwargs)

    @property
    def conversion_rate(self):
        if self.click_count == 0:
            return 0
        return round((self.conversion_count / self.click_count) * 100, 2)

    @property
    def referral_url(self):
        from django.conf import settings
        return f"{settings.FRONTEND_URL}/products/{self.program.product.slug}?ref={self.code}"


class Commission(models.Model):
    """
    Tracks individual commission earned by an affiliate from a referred sale.
    """

    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        APPROVED = "approved", "Approved"
        PAID = "paid", "Paid"
        REJECTED = "rejected", "Rejected"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    affiliate = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="commissions",
    )
    affiliate_link = models.ForeignKey(
        AffiliateLink,
        on_delete=models.CASCADE,
        related_name="commissions",
    )
    order = models.ForeignKey(
        "orders.Order",
        on_delete=models.CASCADE,
        related_name="affiliate_commissions",
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
    )
    paid_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "commissions"
        ordering = ["-created_at"]

    def __str__(self):
        return (
            f"Commission ${self.amount} for {self.affiliate.email} "
            f"({self.status})"
        )
